service: lambda-probot-express

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  router:
    handler: index.probot

    environment:
      LOG_FORMAT: json
      WEBHOOK_SECRET: secret
      APP_ID: 17744

    events:
      - http:
         path: /probot
         method: post
